trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_SERVICE_CONN: 'microservices-acr-conn'  
  IMAGE_TAG: '$(Build.BuildId)'               

steps:

- task: Docker@2
  displayName: Build & Push Node.js Microservice
  inputs:
    containerRegistry: '$(ACR_SERVICE_CONN)'
    repository: 'microservice1'
    command: 'buildAndPush'
    Dockerfile: 'microservice1/Dockerfile'
    tags: '$(IMAGE_TAG)'


- task: Docker@2
  displayName: Build & Push Flask Microservice
  inputs:
    containerRegistry: '$(ACR_SERVICE_CONN)'
    repository: 'microservice2'
    command: 'buildAndPush'
    Dockerfile: 'microservice2/Dockerfile'
    tags: '$(IMAGE_TAG)'

- task: Docker@2
  displayName: Build & Push React Frontend
  inputs:
    containerRegistry: '$(ACR_SERVICE_CONN)'
    repository: 'frontend'
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'
    tags: '$(IMAGE_TAG)'
