name: Push Docker Image to ACR & Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:                    
      ACR_NAME: myprojectacrs              
      RESOURCE_GROUP: MicroservicesRG
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ env.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

     
      - name: Build Docker Image
        run: docker build -t myprojectacrs.azurecr.io/nodejs-micro:latest .

      - name: Log in to ACR
        run: az acr login --name myprojectacrs

      - name: Push Docker Image
        run: docker push myprojectacrs.azurecr.io/nodejs-micro:latest
